name: Deploy Python Hello World

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install  Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: upgrade pip
        run:  python -m pip install --upgrade pip


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy app
        run: python hello.py

